apiVersion: apps/v1
kind: Deployment
metadata:
  name: netbox-housekeeping
spec:
  replicas: 2
  selector:
    matchLabels:
      app: netbox
      role: housekeeping
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: netbox
        role: housekeeping
    spec:
      containers:
        - name: housekeeping
          image: docker.io/netboxcommunity/netbox
          envFrom:
            - configMapRef:
                name: netbox-env
            - secretRef:
                name: netbox-secret-key
          args:
            - /opt/netbox/housekeeping.sh
      tolerations:
      - key: "namespace"
        operator: "Equal"
        value: "staging"
        effect: "NoSchedule"
      nodeSelector:
        name: "app-worker-node"            