apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: netbox
resources:
  - namespace.yaml
  - ../postgres
  - ../redis
  - configmap.yaml
  - housekeeping.yaml
  - worker.yaml
  - server.yaml
  - service.yaml
  - ingress.yaml
