apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: netbox-reports
  labels:
    app: netbox
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
