apiVersion: apps/v1
kind: Deployment
metadata:
  name: netbox-server
spec:
  replicas: 2  # Adjusted replicas to 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: netbox
      role: server
  template:
    metadata:
      labels:
        app: netbox
        role: server
    spec:
      tolerations:
      - key: "namespace"
        operator: "Equal"
        value: "staging"
        effect: "NoSchedule"
      nodeSelector:
        name: "app-worker-node"
      containers:
        - name: server
          image: docker.io/netboxcommunity/netbox  # Corrected image reference
          envFrom:
            - configMapRef:
                name: netbox-env
            - secretRef:
                name: netbox-secret-key
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /api/status/  # Adjusted path for readiness probe
              port: http
            periodSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /api/status/err  # Adjusted path for readiness probe
              port: http
            periodSeconds: 5
            failureThreshold: 3