apiVersion: apps/v1
kind: Deployment
metadata:
  name: netbox-server
spec:
  replicas: 2  # Adjusted replicas to 2
  selector:
    matchLabels:
      app: netbox
      role: server
  template:
    metadata:
      labels:
        app: netbox
        role: server
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - node-01
      containers:
        - name: server
          image: docker.io/netboxcommunity/netbox  # Corrected image reference
          envFrom:
            - configMapRef:
                name: netbox-env
            - secretRef:
                name: netbox-secret-key
          volumeMounts:
            - mountPath: /media
              name: media
            - mountPath: /opt/netbox/netbox/reports
              name: reports
            - mountPath: /opt/netbox/netbox/scripts
              name: scripts
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /api/status/  # Adjusted path for readiness probe
              port: http
            periodSeconds: 5
            failureThreshold: 3
      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: netbox-media
        - name: reports
          persistentVolumeClaim:
            claimName: netbox-reports
        - name: scripts
          persistentVolumeClaim:
            claimName: netbox-scripts
