apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-netbox
  namespace: monitoring  
spec:
  selector:
    matchLabels:
      app: postgres-netbox
  serviceName: postgres-netbox
  replicas: 1
  selector:
    matchLabels:
      app: postgres-netbox
  template:
    metadata:
      labels:
        app: postgres-netbox
    spec:
      tolerations:
      - key: "namespace"
        operator: "Equal"
        value: "staging"
        effect: "NoSchedule"
      nodeSelector:
        name: "app-worker-node"
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app: postgres-netbox
            topologyKey: "kubernetes.io/hostname"
      containers:
        - name: postgres
          image: postgres:14
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-netbox-secret
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-netbox-data
      volumes:
        - name: postgres-netbox-data
          emptyDir: {}    
  # volumeClaimTemplates:
  #   - metadata:
  #       name: postgres-netbox-data
  #     spec:
  #       accessModes:
  #         - ReadWriteOnce
  #       resources:
  #         requests:
  #           storage: 1Gi
